# Generated by Django 3.2.16 on 2022-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/images/man_question.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
